# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        URL="https://secrets-broker-vmaas-ci.5a9f.insights-dev.openshiftapps.com"
        VALIDATION_TOKEN=$(curl -s -X GET -H "x-run-id: $GITHUB_RUN_ID" -H "x-github-repo: $GITHUB_REPOSITORY" -H "x-github-token: ${{ secrets.GITHUB_TOKEN }}" $URL/api/v1/initialize | python -c "import json,sys;sys.stdout.write(json.load(sys.stdin).get('validation_token',''))")
        echo "SECRETS-BROKER-VALIDATION $VALIDATION_TOKEN"
        curl -s -X GET -H "x-run-id: $GITHUB_RUN_ID" -H "x-github-repo: $GITHUB_REPOSITORY" -H "x-github-token: ${{ secrets.GITHUB_TOKEN }}" $URL/api/v1/secrets?keys=TEST_SECRET_1,TEST_SECRET_2
